import { create } from 'zustand'

type ChurrascoStore = {
  valorCarneHomem: number,
  valorCarneMulher: number,
  valorCarneCrianca: number,
  valorPaoDeAlho: number,
  cervejaPessoa: number,
  bebidasNaoAlcoolicas: number,
  valorAguaPessoa: number,
  valorSalGrosso: number,
  valorCarvao: number,
  valorGelo: number,
  homens: number,
  mulheres: number,
  criancas: number,
  temParticipantes: boolean,
  temAssados: boolean,
  tembebidas: boolean,
  bovina: boolean,
  suina: boolean,
  linguica: boolean,
  frango: boolean,
  queijo: boolean,
  paoDeAlho: boolean,
  cerveja: boolean,
  refrigerante: boolean,
  agua: boolean,
  suco: boolean,
  salGrosso: number,
  carvao: number,
  gelo: number
  tempo: Tempo
  totalGramasCarne: number,

}

const useStore = create<ChurrascoStore>()((set) => ({
  valorCarneHomem: 400,
  valorCarneMulher: 300,
  valorCarneCrianca: 200,
  valorPaoDeAlho: 400,
  cervejaPessoa: 1000,
  bebidasNaoAlcoolicas: 600,
  valorAguaPessoa: 200,
  valorSalGrosso: 1000,
  valorCarvao: 5000,
  valorGelo: 1000,
  homens: 0,
  mulheres: 0,
  criancas: 0,
  temParticipantes: false,
  temAssados: false,
  tembebidas: false,
  bovina: false,
  suina: false,
  linguica: false,
  frango: false,
  queijo: false,
  paoDeAlho: false,
  cerveja: false,
  refrigerante: false,
  agua: false,
  suco: false,
  salGrosso: 0,
  carvao: 0,
  gelo: 0,
  tempo: Tempo.quatroHoras,
  totalGramasCarne: 0,
}))

